source 'https://rubygems.org'

gem 'rails', '3.2.12'
gem 'netguru', :git => 'git://github.com/netguru/netguru.git'
gem 'airbrake'

gem 'jquery-rails'

gem 'mongoid'
gem 'netguru-safe'
gem 'newrelic_rpm'
gem 'haml'

group :development do
  gem 'checker'
  gem 'pry'
end

group :test do
  gem 'mongoid-rspec'
end

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end

